//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.28 at 12:26:21 PM CEST 
//


package de.uos.inf.ischedule.model.inrc;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SchedulingPeriodID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Competitor" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="SoftConstraintsPenalty" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="Assignment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="Employee" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ShiftType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "schedulingPeriodID",
    "competitor",
    "softConstraintsPenalty",
    "assignment"
})
@XmlRootElement(name = "Solution")
public class InrcSolution {

    @XmlElement(name = "SchedulingPeriodID", required = true)
    protected String schedulingPeriodID;
    @XmlElement(name = "Competitor", required = true)
    protected Object competitor;
    @XmlElement(name = "SoftConstraintsPenalty", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger softConstraintsPenalty;
    @XmlElement(name = "Assignment")
    protected List<InrcSolution.InrcAssignment> assignment;

    /**
     * Gets the value of the schedulingPeriodID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulingPeriodID() {
        return schedulingPeriodID;
    }

    /**
     * Sets the value of the schedulingPeriodID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulingPeriodID(String value) {
        this.schedulingPeriodID = value;
    }

    /**
     * Gets the value of the competitor property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCompetitor() {
        return competitor;
    }

    /**
     * Sets the value of the competitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCompetitor(Object value) {
        this.competitor = value;
    }

    /**
     * Gets the value of the softConstraintsPenalty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSoftConstraintsPenalty() {
        return softConstraintsPenalty;
    }

    /**
     * Sets the value of the softConstraintsPenalty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSoftConstraintsPenalty(BigInteger value) {
        this.softConstraintsPenalty = value;
    }

    /**
     * Gets the value of the assignment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assignment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssignment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InrcSolution.InrcAssignment }
     * 
     * 
     */
    public List<InrcSolution.InrcAssignment> getAssignment() {
        if (assignment == null) {
            assignment = new ArrayList<InrcSolution.InrcAssignment>();
        }
        return this.assignment;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="Employee" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ShiftType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "date",
        "employee",
        "shiftType"
    })
    public static class InrcAssignment {

        @XmlElement(name = "Date", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "Employee", required = true)
        protected String employee;
        @XmlElement(name = "ShiftType", required = true)
        protected String shiftType;

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the employee property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmployee() {
            return employee;
        }

        /**
         * Sets the value of the employee property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmployee(String value) {
            this.employee = value;
        }

        /**
         * Gets the value of the shiftType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShiftType() {
            return shiftType;
        }

        /**
         * Sets the value of the shiftType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShiftType(String value) {
            this.shiftType = value;
        }

    }

}
