//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.28 at 12:26:20 PM CEST 
//


package de.uos.inf.ischedule.model.inrc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Contracts complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contracts">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Contract" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="SingleAssignmentPerDay" type="{}WeightOnly" minOccurs="0"/>
 *                   &lt;element name="MaxNumAssignments" type="{}OnAndWeight" minOccurs="0"/>
 *                   &lt;element name="MinNumAssignments" type="{}OnAndWeight" minOccurs="0"/>
 *                   &lt;element name="MaxConsecutiveWorkingDays" type="{}OnAndWeight" minOccurs="0"/>
 *                   &lt;element name="MinConsecutiveWorkingDays" type="{}OnAndWeight" minOccurs="0"/>
 *                   &lt;element name="MaxConsecutiveFreeDays" type="{}OnAndWeight" minOccurs="0"/>
 *                   &lt;element name="MinConsecutiveFreeDays" type="{}OnAndWeight" minOccurs="0"/>
 *                   &lt;element name="MaxConsecutiveWorkingWeekends" type="{}OnAndWeight" minOccurs="0"/>
 *                   &lt;element name="MinConsecutiveWorkingWeekends" type="{}OnAndWeight" minOccurs="0"/>
 *                   &lt;element name="MaxWorkingWeekendsInFourWeeks" type="{}OnAndWeight" minOccurs="0"/>
 *                   &lt;element name="WeekendDefinition" type="{}Weekend" minOccurs="0"/>
 *                   &lt;element name="CompleteWeekends" type="{}WeightOnly" minOccurs="0"/>
 *                   &lt;element name="IdenticalShiftTypesDuringWeekend" type="{}WeightOnly" minOccurs="0"/>
 *                   &lt;element name="NoNightShiftBeforeFreeWeekend" type="{}WeightOnly" minOccurs="0"/>
 *                   &lt;element name="TwoFreeDaysAfterNightShifts" type="{}WeightOnly" minOccurs="0"/>
 *                   &lt;element name="AlternativeSkillCategory" type="{}WeightOnly" minOccurs="0"/>
 *                   &lt;element name="UnwantedPatterns" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element name="Pattern" type="{}ID"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/all>
 *                 &lt;attribute name="ID" use="required" type="{}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contracts", propOrder = {
    "contract"
})
public class InrcContracts {

    @XmlElement(name = "Contract", required = true)
    protected List<InrcContracts.InrcContract> contract;

    /**
     * Gets the value of the contract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InrcContracts.InrcContract }
     * 
     * 
     */
    public List<InrcContracts.InrcContract> getContract() {
        if (contract == null) {
            contract = new ArrayList<InrcContracts.InrcContract>();
        }
        return this.contract;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="SingleAssignmentPerDay" type="{}WeightOnly" minOccurs="0"/>
     *         &lt;element name="MaxNumAssignments" type="{}OnAndWeight" minOccurs="0"/>
     *         &lt;element name="MinNumAssignments" type="{}OnAndWeight" minOccurs="0"/>
     *         &lt;element name="MaxConsecutiveWorkingDays" type="{}OnAndWeight" minOccurs="0"/>
     *         &lt;element name="MinConsecutiveWorkingDays" type="{}OnAndWeight" minOccurs="0"/>
     *         &lt;element name="MaxConsecutiveFreeDays" type="{}OnAndWeight" minOccurs="0"/>
     *         &lt;element name="MinConsecutiveFreeDays" type="{}OnAndWeight" minOccurs="0"/>
     *         &lt;element name="MaxConsecutiveWorkingWeekends" type="{}OnAndWeight" minOccurs="0"/>
     *         &lt;element name="MinConsecutiveWorkingWeekends" type="{}OnAndWeight" minOccurs="0"/>
     *         &lt;element name="MaxWorkingWeekendsInFourWeeks" type="{}OnAndWeight" minOccurs="0"/>
     *         &lt;element name="WeekendDefinition" type="{}Weekend" minOccurs="0"/>
     *         &lt;element name="CompleteWeekends" type="{}WeightOnly" minOccurs="0"/>
     *         &lt;element name="IdenticalShiftTypesDuringWeekend" type="{}WeightOnly" minOccurs="0"/>
     *         &lt;element name="NoNightShiftBeforeFreeWeekend" type="{}WeightOnly" minOccurs="0"/>
     *         &lt;element name="TwoFreeDaysAfterNightShifts" type="{}WeightOnly" minOccurs="0"/>
     *         &lt;element name="AlternativeSkillCategory" type="{}WeightOnly" minOccurs="0"/>
     *         &lt;element name="UnwantedPatterns" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element name="Pattern" type="{}ID"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/all>
     *       &lt;attribute name="ID" use="required" type="{}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class InrcContract {

        @XmlElement(name = "SingleAssignmentPerDay")
        protected InrcWeightOnly singleAssignmentPerDay;
        @XmlElement(name = "MaxNumAssignments")
        protected InrcOnAndWeight maxNumAssignments;
        @XmlElement(name = "MinNumAssignments")
        protected InrcOnAndWeight minNumAssignments;
        @XmlElement(name = "MaxConsecutiveWorkingDays")
        protected InrcOnAndWeight maxConsecutiveWorkingDays;
        @XmlElement(name = "MinConsecutiveWorkingDays")
        protected InrcOnAndWeight minConsecutiveWorkingDays;
        @XmlElement(name = "MaxConsecutiveFreeDays")
        protected InrcOnAndWeight maxConsecutiveFreeDays;
        @XmlElement(name = "MinConsecutiveFreeDays")
        protected InrcOnAndWeight minConsecutiveFreeDays;
        @XmlElement(name = "MaxConsecutiveWorkingWeekends")
        protected InrcOnAndWeight maxConsecutiveWorkingWeekends;
        @XmlElement(name = "MinConsecutiveWorkingWeekends")
        protected InrcOnAndWeight minConsecutiveWorkingWeekends;
        @XmlElement(name = "MaxWorkingWeekendsInFourWeeks")
        protected InrcOnAndWeight maxWorkingWeekendsInFourWeeks;
        @XmlElement(name = "WeekendDefinition")
        protected InrcWeekend weekendDefinition;
        @XmlElement(name = "CompleteWeekends")
        protected InrcWeightOnly completeWeekends;
        @XmlElement(name = "IdenticalShiftTypesDuringWeekend")
        protected InrcWeightOnly identicalShiftTypesDuringWeekend;
        @XmlElement(name = "NoNightShiftBeforeFreeWeekend")
        protected InrcWeightOnly noNightShiftBeforeFreeWeekend;
        @XmlElement(name = "TwoFreeDaysAfterNightShifts")
        protected InrcWeightOnly twoFreeDaysAfterNightShifts;
        @XmlElement(name = "AlternativeSkillCategory")
        protected InrcWeightOnly alternativeSkillCategory;
        @XmlElement(name = "UnwantedPatterns")
        protected InrcContracts.InrcContract.InrcUnwantedPatterns unwantedPatterns;
        @XmlElement(name = "Description", required = true)
        protected String description;
        @XmlAttribute(name = "ID", required = true)
        protected String id;

        /**
         * Gets the value of the singleAssignmentPerDay property.
         * 
         * @return
         *     possible object is
         *     {@link InrcWeightOnly }
         *     
         */
        public InrcWeightOnly getSingleAssignmentPerDay() {
            return singleAssignmentPerDay;
        }

        /**
         * Sets the value of the singleAssignmentPerDay property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcWeightOnly }
         *     
         */
        public void setSingleAssignmentPerDay(InrcWeightOnly value) {
            this.singleAssignmentPerDay = value;
        }

        /**
         * Gets the value of the maxNumAssignments property.
         * 
         * @return
         *     possible object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public InrcOnAndWeight getMaxNumAssignments() {
            return maxNumAssignments;
        }

        /**
         * Sets the value of the maxNumAssignments property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public void setMaxNumAssignments(InrcOnAndWeight value) {
            this.maxNumAssignments = value;
        }

        /**
         * Gets the value of the minNumAssignments property.
         * 
         * @return
         *     possible object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public InrcOnAndWeight getMinNumAssignments() {
            return minNumAssignments;
        }

        /**
         * Sets the value of the minNumAssignments property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public void setMinNumAssignments(InrcOnAndWeight value) {
            this.minNumAssignments = value;
        }

        /**
         * Gets the value of the maxConsecutiveWorkingDays property.
         * 
         * @return
         *     possible object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public InrcOnAndWeight getMaxConsecutiveWorkingDays() {
            return maxConsecutiveWorkingDays;
        }

        /**
         * Sets the value of the maxConsecutiveWorkingDays property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public void setMaxConsecutiveWorkingDays(InrcOnAndWeight value) {
            this.maxConsecutiveWorkingDays = value;
        }

        /**
         * Gets the value of the minConsecutiveWorkingDays property.
         * 
         * @return
         *     possible object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public InrcOnAndWeight getMinConsecutiveWorkingDays() {
            return minConsecutiveWorkingDays;
        }

        /**
         * Sets the value of the minConsecutiveWorkingDays property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public void setMinConsecutiveWorkingDays(InrcOnAndWeight value) {
            this.minConsecutiveWorkingDays = value;
        }

        /**
         * Gets the value of the maxConsecutiveFreeDays property.
         * 
         * @return
         *     possible object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public InrcOnAndWeight getMaxConsecutiveFreeDays() {
            return maxConsecutiveFreeDays;
        }

        /**
         * Sets the value of the maxConsecutiveFreeDays property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public void setMaxConsecutiveFreeDays(InrcOnAndWeight value) {
            this.maxConsecutiveFreeDays = value;
        }

        /**
         * Gets the value of the minConsecutiveFreeDays property.
         * 
         * @return
         *     possible object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public InrcOnAndWeight getMinConsecutiveFreeDays() {
            return minConsecutiveFreeDays;
        }

        /**
         * Sets the value of the minConsecutiveFreeDays property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public void setMinConsecutiveFreeDays(InrcOnAndWeight value) {
            this.minConsecutiveFreeDays = value;
        }

        /**
         * Gets the value of the maxConsecutiveWorkingWeekends property.
         * 
         * @return
         *     possible object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public InrcOnAndWeight getMaxConsecutiveWorkingWeekends() {
            return maxConsecutiveWorkingWeekends;
        }

        /**
         * Sets the value of the maxConsecutiveWorkingWeekends property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public void setMaxConsecutiveWorkingWeekends(InrcOnAndWeight value) {
            this.maxConsecutiveWorkingWeekends = value;
        }

        /**
         * Gets the value of the minConsecutiveWorkingWeekends property.
         * 
         * @return
         *     possible object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public InrcOnAndWeight getMinConsecutiveWorkingWeekends() {
            return minConsecutiveWorkingWeekends;
        }

        /**
         * Sets the value of the minConsecutiveWorkingWeekends property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public void setMinConsecutiveWorkingWeekends(InrcOnAndWeight value) {
            this.minConsecutiveWorkingWeekends = value;
        }

        /**
         * Gets the value of the maxWorkingWeekendsInFourWeeks property.
         * 
         * @return
         *     possible object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public InrcOnAndWeight getMaxWorkingWeekendsInFourWeeks() {
            return maxWorkingWeekendsInFourWeeks;
        }

        /**
         * Sets the value of the maxWorkingWeekendsInFourWeeks property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcOnAndWeight }
         *     
         */
        public void setMaxWorkingWeekendsInFourWeeks(InrcOnAndWeight value) {
            this.maxWorkingWeekendsInFourWeeks = value;
        }

        /**
         * Gets the value of the weekendDefinition property.
         * 
         * @return
         *     possible object is
         *     {@link InrcWeekend }
         *     
         */
        public InrcWeekend getWeekendDefinition() {
            return weekendDefinition;
        }

        /**
         * Sets the value of the weekendDefinition property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcWeekend }
         *     
         */
        public void setWeekendDefinition(InrcWeekend value) {
            this.weekendDefinition = value;
        }

        /**
         * Gets the value of the completeWeekends property.
         * 
         * @return
         *     possible object is
         *     {@link InrcWeightOnly }
         *     
         */
        public InrcWeightOnly getCompleteWeekends() {
            return completeWeekends;
        }

        /**
         * Sets the value of the completeWeekends property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcWeightOnly }
         *     
         */
        public void setCompleteWeekends(InrcWeightOnly value) {
            this.completeWeekends = value;
        }

        /**
         * Gets the value of the identicalShiftTypesDuringWeekend property.
         * 
         * @return
         *     possible object is
         *     {@link InrcWeightOnly }
         *     
         */
        public InrcWeightOnly getIdenticalShiftTypesDuringWeekend() {
            return identicalShiftTypesDuringWeekend;
        }

        /**
         * Sets the value of the identicalShiftTypesDuringWeekend property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcWeightOnly }
         *     
         */
        public void setIdenticalShiftTypesDuringWeekend(InrcWeightOnly value) {
            this.identicalShiftTypesDuringWeekend = value;
        }

        /**
         * Gets the value of the noNightShiftBeforeFreeWeekend property.
         * 
         * @return
         *     possible object is
         *     {@link InrcWeightOnly }
         *     
         */
        public InrcWeightOnly getNoNightShiftBeforeFreeWeekend() {
            return noNightShiftBeforeFreeWeekend;
        }

        /**
         * Sets the value of the noNightShiftBeforeFreeWeekend property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcWeightOnly }
         *     
         */
        public void setNoNightShiftBeforeFreeWeekend(InrcWeightOnly value) {
            this.noNightShiftBeforeFreeWeekend = value;
        }

        /**
         * Gets the value of the twoFreeDaysAfterNightShifts property.
         * 
         * @return
         *     possible object is
         *     {@link InrcWeightOnly }
         *     
         */
        public InrcWeightOnly getTwoFreeDaysAfterNightShifts() {
            return twoFreeDaysAfterNightShifts;
        }

        /**
         * Sets the value of the twoFreeDaysAfterNightShifts property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcWeightOnly }
         *     
         */
        public void setTwoFreeDaysAfterNightShifts(InrcWeightOnly value) {
            this.twoFreeDaysAfterNightShifts = value;
        }

        /**
         * Gets the value of the alternativeSkillCategory property.
         * 
         * @return
         *     possible object is
         *     {@link InrcWeightOnly }
         *     
         */
        public InrcWeightOnly getAlternativeSkillCategory() {
            return alternativeSkillCategory;
        }

        /**
         * Sets the value of the alternativeSkillCategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcWeightOnly }
         *     
         */
        public void setAlternativeSkillCategory(InrcWeightOnly value) {
            this.alternativeSkillCategory = value;
        }

        /**
         * Gets the value of the unwantedPatterns property.
         * 
         * @return
         *     possible object is
         *     {@link InrcContracts.InrcContract.InrcUnwantedPatterns }
         *     
         */
        public InrcContracts.InrcContract.InrcUnwantedPatterns getUnwantedPatterns() {
            return unwantedPatterns;
        }

        /**
         * Sets the value of the unwantedPatterns property.
         * 
         * @param value
         *     allowed object is
         *     {@link InrcContracts.InrcContract.InrcUnwantedPatterns }
         *     
         */
        public void setUnwantedPatterns(InrcContracts.InrcContract.InrcUnwantedPatterns value) {
            this.unwantedPatterns = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
         *         &lt;element name="Pattern" type="{}ID"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pattern"
        })
        public static class InrcUnwantedPatterns {

            @XmlElement(name = "Pattern")
            protected List<String> pattern;

            /**
             * Gets the value of the pattern property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the pattern property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPattern().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getPattern() {
                if (pattern == null) {
                    pattern = new ArrayList<String>();
                }
                return this.pattern;
            }

        }

    }

}
