//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.28 at 12:26:20 PM CEST 
//


package de.uos.inf.ischedule.model.inrc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Skills" type="{}Skills" minOccurs="0"/>
 *         &lt;element name="ShiftTypes" type="{}ShiftTypes"/>
 *         &lt;element name="Patterns" type="{}Patterns" minOccurs="0"/>
 *         &lt;element name="Contracts" type="{}Contracts"/>
 *         &lt;element name="Employees" type="{}Employees"/>
 *         &lt;element name="CoverRequirements" type="{}CoverRequirements"/>
 *         &lt;element name="DayOffRequests" type="{}DayOffRequests" minOccurs="0"/>
 *         &lt;element name="DayOnRequests" type="{}DayOnRequests" minOccurs="0"/>
 *         &lt;element name="ShiftOffRequests" type="{}ShiftOffRequests" minOccurs="0"/>
 *         &lt;element name="ShiftOnRequests" type="{}ShiftOnRequests" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OrganisationID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startDate",
    "endDate",
    "skills",
    "shiftTypes",
    "patterns",
    "contracts",
    "employees",
    "coverRequirements",
    "dayOffRequests",
    "dayOnRequests",
    "shiftOffRequests",
    "shiftOnRequests"
})
@XmlRootElement(name = "SchedulingPeriod")
public class InrcSchedulingPeriod {

    @XmlElement(name = "StartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "Skills")
    protected InrcSkills skills;
    @XmlElement(name = "ShiftTypes", required = true)
    protected InrcShiftTypes shiftTypes;
    @XmlElement(name = "Patterns")
    protected InrcPatterns patterns;
    @XmlElement(name = "Contracts", required = true)
    protected InrcContracts contracts;
    @XmlElement(name = "Employees", required = true)
    protected InrcEmployees employees;
    @XmlElement(name = "CoverRequirements", required = true)
    protected InrcCoverRequirements coverRequirements;
    @XmlElement(name = "DayOffRequests")
    protected InrcDayOffRequests dayOffRequests;
    @XmlElement(name = "DayOnRequests")
    protected InrcDayOnRequests dayOnRequests;
    @XmlElement(name = "ShiftOffRequests")
    protected InrcShiftOffRequests shiftOffRequests;
    @XmlElement(name = "ShiftOnRequests")
    protected InrcShiftOnRequests shiftOnRequests;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "OrganisationID")
    protected String organisationID;

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the skills property.
     * 
     * @return
     *     possible object is
     *     {@link InrcSkills }
     *     
     */
    public InrcSkills getSkills() {
        return skills;
    }

    /**
     * Sets the value of the skills property.
     * 
     * @param value
     *     allowed object is
     *     {@link InrcSkills }
     *     
     */
    public void setSkills(InrcSkills value) {
        this.skills = value;
    }

    /**
     * Gets the value of the shiftTypes property.
     * 
     * @return
     *     possible object is
     *     {@link InrcShiftTypes }
     *     
     */
    public InrcShiftTypes getShiftTypes() {
        return shiftTypes;
    }

    /**
     * Sets the value of the shiftTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link InrcShiftTypes }
     *     
     */
    public void setShiftTypes(InrcShiftTypes value) {
        this.shiftTypes = value;
    }

    /**
     * Gets the value of the patterns property.
     * 
     * @return
     *     possible object is
     *     {@link InrcPatterns }
     *     
     */
    public InrcPatterns getPatterns() {
        return patterns;
    }

    /**
     * Sets the value of the patterns property.
     * 
     * @param value
     *     allowed object is
     *     {@link InrcPatterns }
     *     
     */
    public void setPatterns(InrcPatterns value) {
        this.patterns = value;
    }

    /**
     * Gets the value of the contracts property.
     * 
     * @return
     *     possible object is
     *     {@link InrcContracts }
     *     
     */
    public InrcContracts getContracts() {
        return contracts;
    }

    /**
     * Sets the value of the contracts property.
     * 
     * @param value
     *     allowed object is
     *     {@link InrcContracts }
     *     
     */
    public void setContracts(InrcContracts value) {
        this.contracts = value;
    }

    /**
     * Gets the value of the employees property.
     * 
     * @return
     *     possible object is
     *     {@link InrcEmployees }
     *     
     */
    public InrcEmployees getEmployees() {
        return employees;
    }

    /**
     * Sets the value of the employees property.
     * 
     * @param value
     *     allowed object is
     *     {@link InrcEmployees }
     *     
     */
    public void setEmployees(InrcEmployees value) {
        this.employees = value;
    }

    /**
     * Gets the value of the coverRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link InrcCoverRequirements }
     *     
     */
    public InrcCoverRequirements getCoverRequirements() {
        return coverRequirements;
    }

    /**
     * Sets the value of the coverRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link InrcCoverRequirements }
     *     
     */
    public void setCoverRequirements(InrcCoverRequirements value) {
        this.coverRequirements = value;
    }

    /**
     * Gets the value of the dayOffRequests property.
     * 
     * @return
     *     possible object is
     *     {@link InrcDayOffRequests }
     *     
     */
    public InrcDayOffRequests getDayOffRequests() {
        return dayOffRequests;
    }

    /**
     * Sets the value of the dayOffRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link InrcDayOffRequests }
     *     
     */
    public void setDayOffRequests(InrcDayOffRequests value) {
        this.dayOffRequests = value;
    }

    /**
     * Gets the value of the dayOnRequests property.
     * 
     * @return
     *     possible object is
     *     {@link InrcDayOnRequests }
     *     
     */
    public InrcDayOnRequests getDayOnRequests() {
        return dayOnRequests;
    }

    /**
     * Sets the value of the dayOnRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link InrcDayOnRequests }
     *     
     */
    public void setDayOnRequests(InrcDayOnRequests value) {
        this.dayOnRequests = value;
    }

    /**
     * Gets the value of the shiftOffRequests property.
     * 
     * @return
     *     possible object is
     *     {@link InrcShiftOffRequests }
     *     
     */
    public InrcShiftOffRequests getShiftOffRequests() {
        return shiftOffRequests;
    }

    /**
     * Sets the value of the shiftOffRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link InrcShiftOffRequests }
     *     
     */
    public void setShiftOffRequests(InrcShiftOffRequests value) {
        this.shiftOffRequests = value;
    }

    /**
     * Gets the value of the shiftOnRequests property.
     * 
     * @return
     *     possible object is
     *     {@link InrcShiftOnRequests }
     *     
     */
    public InrcShiftOnRequests getShiftOnRequests() {
        return shiftOnRequests;
    }

    /**
     * Sets the value of the shiftOnRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link InrcShiftOnRequests }
     *     
     */
    public void setShiftOnRequests(InrcShiftOnRequests value) {
        this.shiftOnRequests = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the organisationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganisationID() {
        return organisationID;
    }

    /**
     * Sets the value of the organisationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganisationID(String value) {
        this.organisationID = value;
    }

}
