//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.28 at 12:26:20 PM CEST 
//


package de.uos.inf.ischedule.model.inrc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Weekend.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Weekend">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SaturdaySunday"/>
 *     &lt;enumeration value="FridaySaturdaySunday"/>
 *     &lt;enumeration value="FridaySaturdaySundayMonday"/>
 *     &lt;enumeration value="SaturdaySundayMonday"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Weekend")
@XmlEnum
public enum InrcWeekend {

    @XmlEnumValue("SaturdaySunday")
    SATURDAY_SUNDAY("SaturdaySunday"),
    @XmlEnumValue("FridaySaturdaySunday")
    FRIDAY_SATURDAY_SUNDAY("FridaySaturdaySunday"),
    @XmlEnumValue("FridaySaturdaySundayMonday")
    FRIDAY_SATURDAY_SUNDAY_MONDAY("FridaySaturdaySundayMonday"),
    @XmlEnumValue("SaturdaySundayMonday")
    SATURDAY_SUNDAY_MONDAY("SaturdaySundayMonday");
    private final String value;

    InrcWeekend(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InrcWeekend fromValue(String v) {
        for (InrcWeekend c: InrcWeekend.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
