//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.28 at 12:26:20 PM CEST 
//


package de.uos.inf.ischedule.model.inrc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.uos.inf.ischedule.model.inrc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.uos.inf.ischedule.model.inrc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InrcShiftOnRequests }
     * 
     */
    public InrcShiftOnRequests createInrcShiftOnRequests() {
        return new InrcShiftOnRequests();
    }

    /**
     * Create an instance of {@link InrcShiftOffRequests }
     * 
     */
    public InrcShiftOffRequests createInrcShiftOffRequests() {
        return new InrcShiftOffRequests();
    }

    /**
     * Create an instance of {@link InrcDayOnRequests }
     * 
     */
    public InrcDayOnRequests createInrcDayOnRequests() {
        return new InrcDayOnRequests();
    }

    /**
     * Create an instance of {@link InrcDayOffRequests }
     * 
     */
    public InrcDayOffRequests createInrcDayOffRequests() {
        return new InrcDayOffRequests();
    }

    /**
     * Create an instance of {@link InrcCoverRequirements }
     * 
     */
    public InrcCoverRequirements createInrcCoverRequirements() {
        return new InrcCoverRequirements();
    }

    /**
     * Create an instance of {@link InrcEmployees }
     * 
     */
    public InrcEmployees createInrcEmployees() {
        return new InrcEmployees();
    }

    /**
     * Create an instance of {@link InrcEmployees.InrcEmployee }
     * 
     */
    public InrcEmployees.InrcEmployee createInrcEmployeesInrcEmployee() {
        return new InrcEmployees.InrcEmployee();
    }

    /**
     * Create an instance of {@link InrcContracts }
     * 
     */
    public InrcContracts createInrcContracts() {
        return new InrcContracts();
    }

    /**
     * Create an instance of {@link InrcContracts.InrcContract }
     * 
     */
    public InrcContracts.InrcContract createInrcContractsInrcContract() {
        return new InrcContracts.InrcContract();
    }

    /**
     * Create an instance of {@link InrcPatterns }
     * 
     */
    public InrcPatterns createInrcPatterns() {
        return new InrcPatterns();
    }

    /**
     * Create an instance of {@link InrcPatterns.InrcPattern }
     * 
     */
    public InrcPatterns.InrcPattern createInrcPatternsInrcPattern() {
        return new InrcPatterns.InrcPattern();
    }

    /**
     * Create an instance of {@link InrcPatterns.InrcPattern.InrcPatternEntries }
     * 
     */
    public InrcPatterns.InrcPattern.InrcPatternEntries createInrcPatternsInrcPatternInrcPatternEntries() {
        return new InrcPatterns.InrcPattern.InrcPatternEntries();
    }

    /**
     * Create an instance of {@link InrcShiftTypes }
     * 
     */
    public InrcShiftTypes createInrcShiftTypes() {
        return new InrcShiftTypes();
    }

    /**
     * Create an instance of {@link InrcShiftTypes.InrcShift }
     * 
     */
    public InrcShiftTypes.InrcShift createInrcShiftTypesInrcShift() {
        return new InrcShiftTypes.InrcShift();
    }

    /**
     * Create an instance of {@link InrcSchedulingPeriod }
     * 
     */
    public InrcSchedulingPeriod createInrcSchedulingPeriod() {
        return new InrcSchedulingPeriod();
    }

    /**
     * Create an instance of {@link de.uos.inf.ischedule.model.inrc.InrcSkills }
     * 
     */
    public de.uos.inf.ischedule.model.inrc.InrcSkills createInrcSkills() {
        return new de.uos.inf.ischedule.model.inrc.InrcSkills();
    }

    /**
     * Create an instance of {@link InrcOnAndWeight }
     * 
     */
    public InrcOnAndWeight createInrcOnAndWeight() {
        return new InrcOnAndWeight();
    }

    /**
     * Create an instance of {@link InrcWeightOnly }
     * 
     */
    public InrcWeightOnly createInrcWeightOnly() {
        return new InrcWeightOnly();
    }

    /**
     * Create an instance of {@link InrcCover }
     * 
     */
    public InrcCover createInrcCover() {
        return new InrcCover();
    }

    /**
     * Create an instance of {@link InrcConstraintAttributes }
     * 
     */
    public InrcConstraintAttributes createInrcConstraintAttributes() {
        return new InrcConstraintAttributes();
    }

    /**
     * Create an instance of {@link InrcShiftOnRequests.InrcShiftOn }
     * 
     */
    public InrcShiftOnRequests.InrcShiftOn createInrcShiftOnRequestsInrcShiftOn() {
        return new InrcShiftOnRequests.InrcShiftOn();
    }

    /**
     * Create an instance of {@link InrcShiftOffRequests.InrcShiftOff }
     * 
     */
    public InrcShiftOffRequests.InrcShiftOff createInrcShiftOffRequestsInrcShiftOff() {
        return new InrcShiftOffRequests.InrcShiftOff();
    }

    /**
     * Create an instance of {@link InrcDayOnRequests.InrcDayOn }
     * 
     */
    public InrcDayOnRequests.InrcDayOn createInrcDayOnRequestsInrcDayOn() {
        return new InrcDayOnRequests.InrcDayOn();
    }

    /**
     * Create an instance of {@link InrcDayOffRequests.InrcDayOff }
     * 
     */
    public InrcDayOffRequests.InrcDayOff createInrcDayOffRequestsInrcDayOff() {
        return new InrcDayOffRequests.InrcDayOff();
    }

    /**
     * Create an instance of {@link InrcCoverRequirements.InrcDayOfWeekCover }
     * 
     */
    public InrcCoverRequirements.InrcDayOfWeekCover createInrcCoverRequirementsInrcDayOfWeekCover() {
        return new InrcCoverRequirements.InrcDayOfWeekCover();
    }

    /**
     * Create an instance of {@link InrcCoverRequirements.InrcDateSpecificCover }
     * 
     */
    public InrcCoverRequirements.InrcDateSpecificCover createInrcCoverRequirementsInrcDateSpecificCover() {
        return new InrcCoverRequirements.InrcDateSpecificCover();
    }

    /**
     * Create an instance of {@link InrcEmployees.InrcEmployee.InrcSkills }
     * 
     */
    public InrcEmployees.InrcEmployee.InrcSkills createInrcEmployeesInrcEmployeeInrcSkills() {
        return new InrcEmployees.InrcEmployee.InrcSkills();
    }

    /**
     * Create an instance of {@link InrcContracts.InrcContract.InrcUnwantedPatterns }
     * 
     */
    public InrcContracts.InrcContract.InrcUnwantedPatterns createInrcContractsInrcContractInrcUnwantedPatterns() {
        return new InrcContracts.InrcContract.InrcUnwantedPatterns();
    }

    /**
     * Create an instance of {@link InrcPatterns.InrcPattern.InrcPatternEntries.InrcPatternEntry }
     * 
     */
    public InrcPatterns.InrcPattern.InrcPatternEntries.InrcPatternEntry createInrcPatternsInrcPatternInrcPatternEntriesInrcPatternEntry() {
        return new InrcPatterns.InrcPattern.InrcPatternEntries.InrcPatternEntry();
    }

    /**
     * Create an instance of {@link InrcShiftTypes.InrcShift.InrcSkills }
     * 
     */
    public InrcShiftTypes.InrcShift.InrcSkills createInrcShiftTypesInrcShiftInrcSkills() {
        return new InrcShiftTypes.InrcShift.InrcSkills();
    }
    

    /**
     * Create an instance of {@link InrcSolution }
     * 
     */
    public InrcSolution createInrcSolution() {
        return new InrcSolution();
    }

    /**
     * Create an instance of {@link InrcSolution.InrcAssignment }
     * 
     */
    public InrcSolution.InrcAssignment createInrcSolutionInrcAssignment() {
        return new InrcSolution.InrcAssignment();
    }


}
